### ISSUE TITLE
Fails to build due to: libkimera_semantics_ros undefined reference to cv::String::deallocate()

### ISSUE THREAD

**Issue by btalb** [MIT-SPARK/Kimera-Semantics#71]
Fails to build with the above error on Ubuntu 20.04 when following the instructions in the README.

The `kimera_semantics_ros` library seems to be missing linking against OpenCV. 

I added the following lines, which link against the same `opencv3_catkin` package used in Kimera-VIO-ROS (https://github.com/MIT-SPARK/Kimera-VIO-ROS/blob/master/install/kimera_vio_ros_https.rosinstall):

```cmake
find_package(opencv3_catkin REQUIRED)
```
```cmake
target_link_libraries(${PROJECT_NAME} ${opencv3_catkin_LIBRARIES})
```

After these lines were added, the ROS stack successfully builds with Noetic on Ubuntu 20.04.

**Comment by hellovuong** [comment]
thank you, your note about building on Ubuntu 20.04 is really helpful.
